// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_FKXbdMZj7mj71_LzCVkcrTSFDwC5bEM',
    appId: '1:286843489171:web:570bbb9456517478483666',
    messagingSenderId: '286843489171',
    projectId: 'testnotifications-2efc1',
    authDomain: 'testnotifications-2efc1.firebaseapp.com',
    storageBucket: 'testnotifications-2efc1.appspot.com',
    measurementId: 'G-0S2QQV2MBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBklx_7X-CE0xzoUsF38TJj7243yvGaDfc',
    appId: '1:286843489171:android:f0179122538551fa483666',
    messagingSenderId: '286843489171',
    projectId: 'testnotifications-2efc1',
    storageBucket: 'testnotifications-2efc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8hzCxQrWR_UxW5ePbF4GQ-WWu4rIpobk',
    appId: '1:286843489171:ios:8d50e26ef283a106483666',
    messagingSenderId: '286843489171',
    projectId: 'testnotifications-2efc1',
    storageBucket: 'testnotifications-2efc1.appspot.com',
    iosBundleId: 'com.example.userApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8hzCxQrWR_UxW5ePbF4GQ-WWu4rIpobk',
    appId: '1:286843489171:ios:8d50e26ef283a106483666',
    messagingSenderId: '286843489171',
    projectId: 'testnotifications-2efc1',
    storageBucket: 'testnotifications-2efc1.appspot.com',
    iosBundleId: 'com.example.userApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_FKXbdMZj7mj71_LzCVkcrTSFDwC5bEM',
    appId: '1:286843489171:web:53323453ca8a8022483666',
    messagingSenderId: '286843489171',
    projectId: 'testnotifications-2efc1',
    authDomain: 'testnotifications-2efc1.firebaseapp.com',
    storageBucket: 'testnotifications-2efc1.appspot.com',
    measurementId: 'G-VSJ3Z1E4RD',
  );
}
